Task/registration view
holyjim/cva pull request #15
Opened 2018-10-14 23:43 UTC by ervine13

2018-10-14 23:44 UTC, ervine13 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Registration: Create registration form UI](https://trello.com/c/JAyPmjih/31-registration-create-registration-form-ui)

2018-10-15 00:19 UTC, ashwinjv requested changes

2018-10-15 00:19 UTC, ashwinjv commented on src/app/accounts/register/register.component.html
> +  <mat-tab-group mat-stretch-tabs color="accent" backgroundColor="primary">
Do you want to add a max width? and center that so that it does not look stretched out in bigger screens?

2018-10-15 00:19 UTC, ashwinjv commented on src/app/accounts/register/register.component.spec.ts
> +  // });
we can delete this :)

2018-10-15 00:19 UTC, ashwinjv commented on src/app/accounts/register/register.component.html
> +          <input matInput placeholder="Department" [class.is-danger]="department.invalid && department.dirty"
Can we make this a select? and select from the Department enum values?

2018-10-15 00:19 UTC, ashwinjv commented on src/app/accounts/register/register.component.ts
> +  get password() { return this.registrationForm.get('password'); }
I like the getters :)

2018-10-15 00:19 UTC, ashwinjv commented on src/app/app.component.spec.ts
> +        ReactiveFormsModule,
You need ReactiveFormsModule for the app component spec?

2018-10-15 00:53 UTC, ervine13 commented on src/app/accounts/register/register.component.html
> +  <mat-tab-group mat-stretch-tabs color="accent" backgroundColor="primary">
yea. intentionally didn't do that w this PR. just wanted func first.  you good w that?

2018-10-15 00:54 UTC, ervine13 commented on src/app/accounts/register/register.component.spec.ts
> +  // });
will do

2018-10-15 00:55 UTC, ervine13 commented on src/app/app.component.spec.ts
> +        ReactiveFormsModule,
yea, it was failing without it

2018-10-15 00:55 UTC, ervine13 commented on src/app/accounts/register/register.component.html
> +          <input matInput placeholder="Department" [class.is-danger]="department.invalid && department.dirty"
wil do

2018-10-15 00:59 UTC, ashwinjv commented on src/app/accounts/register/register.component.html
> +  <mat-tab-group mat-stretch-tabs color="accent" backgroundColor="primary">
👍

2018-10-15 01:02 UTC, ashwinjv commented on src/app/app.component.spec.ts
> +        ReactiveFormsModule,
I just pulled your branch and deleted that line and tests passed .. I am missing something?

2018-10-15 05:36 UTC, ervine13 commented on src/app/accounts/register/register.component.html
> +  <mat-tab-group mat-stretch-tabs color="accent" backgroundColor="primary">
fixed

2018-10-15 05:40 UTC, ervine13 commented on src/app/app.component.spec.ts
> +        ReactiveFormsModule,
you're right. I added to app.component, i only need it on registration component. fixed

2018-10-15 14:15 UTC, ashwinjv approved these changes

2018-10-15 14:16 UTC, merged